export const VACCINE_INFO_REQUEST = 'VACCINE_INFO_REQUEST'
export const VACCINE_INFO_SUCCESS = 'VACCINE_INFO_SUCCESS'
export const VACCINE_INFO_FAIL = 'VACCINE_INFO_FAIL'


export const VACCINE_DETAILS_REQUEST = 'VACCINE_DETAILS_REQUEST'
export const VACCINE_DETAILS_SUCCESS = 'VACCINE_DETAILS_SUCCESS'
export const VACCINE_DETAILS_FAIL = 'VACCINE_DETAILS_FAIL'


export const VACCINE_UPDATE_REQUEST = 'VACCINE_UPDATE_REQUEST'
export const VACCINE_UPDATE_SUCCESS = 'VACCINE_UPDATE_SUCCESS'
export const VACCINE_UPDATE_FAIL = 'VACCINE_UPDATE_FAIL'
export const VACCINE_UPLOAD_SUCCESS = 'VACCINE_UPLOAD_SUCCESS'

export const VACCINE_UPLOADURL_REQUEST = 'VACCINE_UPLOADURL_REQUEST'
export const VACCINE_UPLOADURL_SUCCESS = 'VACCINE_UPLOADURL_SUCCESS'
export const VACCINE_UPLOADURL_FAIL = 'VACCINE_UPLOADURL_FAIL'

export const VACCINE_DELETE_REQUEST = 'VACCINE_DELETE_REQUEST'
export const VACCINE_DELETE_SUCCESS = 'VACCINE_DELETE_SUCCESS'
export const VACCINE_DELETE_FAIL = 'VACCINE_DELETE_FAIL'